language: node_js

node_js:
- '6'

os:
- linux
- osx

install:
- npm install -g vsce
- npm install -g typescript
- npm install -g gulp
- npm install

script:
- gulp tslint
- vsce package
- npm test --silent