name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger:
  branches:
    include:
      - main
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: linux
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-9181-Tool
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            displayName: VSCode-Java-Debug-CI
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: vsix
                  targetPath: $(Build.ArtifactStagingDirectory)/vsix
                  displayName: "Publish Artifact: vsix"
            steps:
              - checkout: self
                fetchTags: true
              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled
              - task: Npm@1
                displayName: npm install
                inputs:
                  verbose: false
              - task: CmdLine@2
                displayName: build server
                inputs:
                  script: |-
                    git clone https://github.com/microsoft/java-debug ../java-debug
                    npm run build-server
              - task: CmdLine@2
                displayName: vsce package
                inputs:
                  script: npx @vscode/vsce@latest package
              - task: CopyFiles@2
                displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)/vsix"
                inputs:
                  Contents: "*.vsix"
                  TargetFolder: $(Build.ArtifactStagingDirectory)/vsix
